package com.example.team_foxhound.minicapstone_project.InformationCatalog;////
//
//  Generated by StarUML(tm) Java Add-In
// @ Company: @FOXHOUND.INC
//  @ Project : @FitnessCompanion
//  @ Author : @Ahmed, Nitesh, Nauman, Philippe
//
//


import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

import com.example.team_foxhound.minicapstone_project.Interfaces.InfoCatalogInterface;
import com.example.team_foxhound.minicapstone_project.Interfaces.InterfaceHandler;
import com.example.team_foxhound.minicapstone_project.MainActivity;

import persistence.Handler;

public class InfoCatalog extends MainActivity {
    public int[] getInfo() {
        return new int[0];
    }

    public void storeInfo(int age, int height,int weight) {
        InterfaceHandler handler=new Handler(contextnew);
        handler.putUserInfo(age,height,weight);

    }

}
