////
////
////  Generated by StarUML(tm) Java Add-In
//// @ Company: @FOXHOUND.INC
////  @ Project : @FitnessCompanion
////  @ Author : @Ahmed, Nitesh, Nauman, Philippe
////
////
//
//
//import com.example.team_foxhound.minicapstone_project.Interfaces.InfoCatalogInterface;
//
//public class InfoCatalog implements InfoCatalogInterface{
//	public int[0...*] getInfo() {
//
//	}
//
//	public void storeInfo(Object int[0..*]) {
//
//	}
//}
