package com.example.team_foxhound.minicapstone_project.InformationCatalog;////
//
//  Generated by StarUML(tm) Java Add-In
// @ Company: @FOXHOUND.INC
//  @ Project : @FitnessCompanion
//  @ Author : @Ahmed, Nitesh, Nauman, Philippe
//
//


import com.example.team_foxhound.minicapstone_project.Interfaces.InterfaceHandler;
import com.example.team_foxhound.minicapstone_project.Activities.MainActivity;
import com.example.team_foxhound.minicapstone_project.UserManagement.SubUser;

import persistence.Handler;

public class InfoCatalog {
    public int[] getInfo() {
        return new int[0];
    }

//    SubUser subuser = new SubUser();
//    int age = subuser.age;
//    int height = subuser.height;
//    int weight = subuser.weight;

    public void storeInfo(SubUser user)
    {
        InterfaceHandler handler=new Handler(null);
        handler.putUserInfo(user.age,user.height,user.weight);


    }

}
