//
//
//  Generated by StarUML(tm) Java Add-In
// @ Company: @FOXHOUND.INC
//  @ Project : @FitnessCompanion 
//  @ Author : @Ahmed, Nitesh, Nauman, Philippe
//
//


import com.example.team_foxhound.minicapstone_project.Interfaces.MusicCatalogInterface;

public class MusicCatalog implements MusicCatalogInterface{
    public MusicCatalog() {

    }

    public MusicCatalog() {

    }

    public MusicCatalog() {

    }
}
