//
//
//  Generated by StarUML(tm) Java Add-In
// @ Company: @FOXHOUND.INC
//  @ Project : @FitnessCompanion
//  @ Author : @Ahmed, Nitesh, Nauman, Philippe
//
//


import com.example.team_foxhound.minicapstone_project.Interfaces.MusicCatalogInterface;

public class MusicCatalog implements MusicCatalogInterface{

    @Override
    public String getPath() {
        return null;
    }

    @Override
    public int getBbm() {
        return 0;
    }

    @Override
    public String getName() {
        return null;
    }
}
