package com.example.team_foxhound.minicapstone_project.InformationCatalog;//
//
//  Generated by StarUML(tm) Java Add-In
// @ Company: @FOXHOUND.INC
//  @ Project : @FitnessCompanion
//  @ Author : @Ahmed, Nitesh, Nauman, Philippe
//
//


import com.example.team_foxhound.minicapstone_project.Interfaces.UserCatalogInterface;

public class UserCatalog implements UserCatalogInterface {
	public void registerUser(String username, String password, String firstname, String lastname) {

	}

	public void deleteUser(String username) {

	}
}
