package com.example.team_foxhound.minicapstone_project.InformationCatalog;//
//
//  Generated by StarUML(tm) Java Add-In
// @ Company: @FOXHOUND.INC
//  @ Project : @FitnessCompanion
//  @ Author : @Ahmed, Nitesh, Nauman, Philippe
//
//


import com.example.team_foxhound.minicapstone_project.Interfaces.UserCatalogInterface;
import com.example.team_foxhound.minicapstone_project.UserManagement.SuperUser;

public abstract class UserCatalog implements UserCatalogInterface  {

	public void registerUser(SuperUser superUser) {
	}

	public void deleteUser(String username) {

	}
}
