//
//
//  Generated by StarUML(tm) Java Add-In
// @ Company: @FOXHOUND.INC
//  @ Project : @FitnessCompanion 
//  @ Author : @Ahmed, Nitesh, Nauman, Philippe
//
//




public class Admin extends SuperUser {
	public SubUser composition;
	public void modifyProfile() {
	
	}
	
	public void modifySubProfile(Subuser user) {
	
	}
}
