////
////
////  Generated by StarUML(tm) Java Add-In
//// @ Company: @FOXHOUND.INC
////  @ Project : @FitnessCompanion
////  @ Author : @Ahmed, Nitesh, Nauman, Philippe
////
////
//
//
//import com.example.team_foxhound.minicapstone_project.UserManagement.SuperUser;
//
//public class Admin extends SuperUser {
//	public SubUser composition;
//	public final void modifyProfile() {
//
//	}
//
//	public void modifySubProfile(Subuser user) {
//
//	}
//}
