//
//
//  Generated by StarUML(tm) Java Add-In
// @ Company: @FOXHOUND.INC
//  @ Project : @FitnessCompanion 
//  @ Author : @Ahmed, Nitesh, Nauman, Philippe
//
//




public class SubUser extends SuperUser {
	public int age;
	public int weight;
	public int height;
	public void modifyProfile() {
	
	}
	
	public void setPreferences(bool[0...*] preferences, int Type) {
	
	}
}
