package com.example.team_foxhound.minicapstone_project.UserManagement;//
//
//  Generated by StarUML(tm) Java Add-In
// @ Company: @FOXHOUND.INC
//  @ Project : @FitnessCompanion
//  @ Author : @Ahmed, Nitesh, Nauman, Philippe
//
//


import com.example.team_foxhound.minicapstone_project.InformationCatalog.RegisterInfo;

public class SubUser extends RegisterInfo {
	public int age;
	public int weight;
	public int height;
	public String firstName;
	public String lastName;
	public String userName;
	public String password;

	SubUser() {

        age = 0;
        weight = 0;
        height = 0;
        firstName = "";
        lastName = "";
        password = "";
    }




/*//    EditText username = (EditText)findViewById(R.id.editText);

        userName = "";//    EditText password = (EditText)findViewById(R.id.editText3);

//	user.setfName(username);
//	user.setlName(lastName);
//	user.setUsername(username);
//	user.setPassword(password);*/

	public void setAge(int Age){age =Age;}
    public void setWeight(int Weight){weight = Weight;}
    public void setHeight(int Height) {height = Height;}

    public final void modifyProfile() {}

	public void setPreferences(UserPreferences preferences, int Type) {}


	public void setfname(SubUser subUser, String s) {subUser.firstName= s;}
	public void setlname(SubUser subUser,String s) {
		subUser.lastName= s;
	}
	public void setusername(SubUser subUser,String s) {subUser.userName= s;}
	public void setpassword(SubUser subUser,String s) {
		subUser.password = s;
	}

	public String getfname(String s){return firstName;}
}
