package com.example.team_foxhound.minicapstone_project.UserManagement;//
//
//  Generated by StarUML(tm) Java Add-In
// @ Company: @FOXHOUND.INC
//  @ Project : @FitnessCompanion
//  @ Author : @Ahmed, Nitesh, Nauman, Philippe
//
//


import android.text.Editable;

import com.example.team_foxhound.minicapstone_project.Activities.UserInfoActivity;

public class SubUser extends UserInfoActivity {
	public int age;
	public int weight;
	public int height;

		public SubUser(){
			setAge();
			setHeight();
			setWeight();

		}

//    EditText username = (EditText)findViewById(R.id.editText);
//    EditText password = (EditText)findViewById(R.id.editText3);

//	user.setfName(username);
//	user.setlName(lastName);
//	user.setUsername(username);
//	user.setPassword(password);

	public void setAge(){

		age = Integer.valueOf(editText.getText().toString()).intValue();
	}


	public void setWeight(){

		weight = Integer.valueOf(editText3.getText().toString()).intValue();
	}

	public void setHeight(){

		height = Integer.valueOf(editText2.getText().toString()).intValue();
	}


	public final void modifyProfile() {

	}

	public void setPreferences(Boolean[] preferences, int Type) {

	}


}
