//
//
//  Generated by StarUML(tm) Java Add-In
// @ Company: @FOXHOUND.INC
//  @ Project : @FitnessCompanion 
//  @ Author : @Ahmed, Nitesh, Nauman, Philippe
//
//




public class SuperUser {
	public string firstName;
	public string lastName;
	public string username;
	public string password;
	public void modifyProfile() {
	
	}
}
