package com.example.team_foxhound.minicapstone_project.UserManagement;//
//
//  Generated by StarUML(tm) Java Add-In
// @ Company: @FOXHOUND.INC
//  @ Project : @FitnessCompanion
//  @ Author : @Ahmed, Nitesh, Nauman, Philippe
//
//


import com.example.team_foxhound.minicapstone_project.Activities.MainActivity;

public abstract class SuperUser extends MainActivity {
	private String firstName;
	public String lastName;
	public String username;
	public String password;
	public void modifyProfile(){};



}
