////
////
////  Generated by StarUML(tm) Java Add-In
//// @ Company: @FOXHOUND.INC
////  @ Project : @FitnessCompanion
////  @ Author : @Ahmed, Nitesh, Nauman, Philippe
////
////
//
//
//
//
//public class UserPreferences {
//	public int typeofworkout;
//	public bool showUIelements;
//}
