package com.example.team_foxhound.minicapstone_project.UserManagement;//
//
//  Generated by StarUML(tm) Java Add-In
// @ Company: @FOXHOUND.INC
//  @ Project : @FitnessCompanion
//  @ Author : @Ahmed, Nitesh, Nauman, Philippe
//
//




public class UserPreferences {
	public int typeofworkout;
	private Boolean showUIelements;
}
