package com.example.team_foxhound.minicapstone_project.AlgorithmGenerator;//
//
//  Generated by StarUML(tm) Java Add-In
// @ Company: @FOXHOUND.INC
//  @ Project : @FitnessCompanion
//  @ Author : @Ahmed, Nitesh, Nauman, Philippe
//
//


import com.example.team_foxhound.minicapstone_project.Interfaces.AlgorithmGeneratorInterface;
import com.example.team_foxhound.minicapstone_project.UserManagement.UserPreferences;

import android.os.Vibrator;
public class AlgorithmGenerator implements AlgorithmGeneratorInterface {
    private Object HBcurrFromSensor;

    public int CalculateHBmax(Object age,String workoutType) {
    int sample=0;
        return sample;
	}

	public int CalculateTHBmax(int HBmax, UserPreferences preferences) {
        int sample2=0;
        return sample2;
	}

	public void TriggerVib(int HBcurr,int TargetHB) {
        //Vibrator vib;

//		if(HBcurrFromSensor>getTargetHB())
//		{
//			vib.vibrate(long[] pattern, int repeat, AudioAttributes attributes);
//			if(HBcurrFromSensor<getTargetHB())
//			{vib.vibrate(long[] patternnew, int repeatnew, AudioAttributes attributesnew);}
//		}


    }

    @Override
    public int ComputeCal(Object ageLint, int weight, int height, int distance) {
        return 0;
    }
}
