package com.example.team_foxhound.minicapstone_project.AlgorithmGenerator;//
//
//  Generated by StarUML(tm) Java Add-In
// @ Company: @FOXHOUND.INC
//  @ Project : @FitnessCompanion 
//  @ Author : @Ahmed, Nitesh, Nauman, Philippe
//
//


import com.example.team_foxhound.minicapstone_project.Interfaces.AlgorithmGeneratorInterface;

public class AlgorithmGenerator implements AlgorithmGeneratorInterface,HeartBeatSensorAPI, HeartBeatSensorAPI, VibrationAPI {
	public int CalculateHBmax(Object age;string) {
	
	}
	
	public int CalculateTHBmax(int HBmax, UserPreferences preferences) {
	
	}
	
	public void TriggerVib(int HBcurr, int targetHB) {
	
	}
	
	public int ComputeCal(Object ageLint, int weight, int height, int distance) {
	
	}
}
