package com.example.team_foxhound.minicapstone_project.AlgorithmGenerator;//
//
//  Generated by StarUML(tm) Java Add-In
// @ Company: @FOXHOUND.INC
//  @ Project : @FitnessCompanion
//  @ Author : @Ahmed, Nitesh, Nauman, Philippe
//
//


import com.example.team_foxhound.minicapstone_project.Activities.RegistrationConfirmation;
import com.example.team_foxhound.minicapstone_project.Interfaces.AlgorithmGeneratorInterface;
import com.example.team_foxhound.minicapstone_project.UserManagement.UserPreferences;

import android.os.Vibrator;
public class AlgorithmGenerator   extends RegistrationConfirmation implements AlgorithmGeneratorInterface {


    public int CalculateHBmax(int age) { // String workoutType, aerdd aft

        int HBMAX;
        HBMAX = 220 - age;

        return HBMAX;
	}


	public int CalculateTHBmax(int HBmax, UserPreferences preferences) {

        int sample2=0;
        return sample2;
	}

	public void TriggerVib(int HBcurr,int TargetHB) {
        //Vibrator vib;

//		if(HBcurrFromSensor>getTargetHB())
//		{
//			vib.vibrate(long[] pattern, int repeat, AudioAttributes attributes);
//			if(HBcurrFromSensor<getTargetHB())
//			{vib.vibrate(long[] patternnew, int repeatnew, AudioAttributes attributesnew);}
//		}


    }

    @Override
    public int ComputeCal(Object ageLint, int weight, int height, int distance) {
        return 0;
    }
}
